# Generated by Django 4.0.8 on 2023-08-18 00:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField()),
                ('est_verifie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_lot', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
                ('reception_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField()),
                ('presentation', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Expires Soon', 'Expires Soon (2 months)')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sauvegarde', models.DateTimeField(auto_now_add=True)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='check_in_Histories/')),
                ('remark_item', models.CharField(blank=True, max_length=500, null=True)),
                ('remark_medicine', models.CharField(blank=True, max_length=500, null=True)),
                ('other_file', models.FileField(blank=True, null=True, upload_to='other_files/')),
            ],
        ),
        
        
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_lot', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
                ('reception_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField()),
                ('presentation', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('origin', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('family_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='Single', max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=45, null=True)),
                ('job_position', models.CharField(blank=True, max_length=45, null=True)),
                ('risk', models.TextField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='stock_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='stock_users', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='VisiteMedicaleSpontanee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('oxygen_saturation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_glucose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        
        migrations.CreateModel(
            name='OutStockMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
            ],
        ),
       
    ]
