# Generated by Django 4.0.8 on 2023-08-18 23:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dossiermedical_systematique_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='area',
            field=models.CharField(blank=True, choices=[('CCR', 'CCR'), ('SOLAR FIELD', 'SOLAR FIELD'), ('ADMINISTRATION OFFICE', 'ADMINISTRATION OFFICE'), ('WTP', 'WTP'), ('WORKSHOP', 'WORKSHOP'), ('WAREHOUSE', 'WAREHOUSE')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='risk',
            field=models.FileField(blank=True, null=True, upload_to='risk_files/')),
    ]
