# Generated by Django 4.0.8 on 2023-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patient_area_alter_patient_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='ant_professionneles',
            field=models.CharField(default='RAS', max_length=100),
        ),
    ]
