# Generated by Django 4.0.8 on 2023-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_systematique_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systematique',
            name='controle',
            field=models.CharField(default='RAS', max_length=20),
        ),
    ]
