# Generated by Django 4.0.8 on 2023-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_systematique_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='systematique',
            name='GB',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='HB',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='albumine',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='amygdales',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='hernies',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='lympho',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='plq',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AddField(
            model_name='systematique',
            name='sucre',
            field=models.CharField(default='RAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='systematique',
            name='commentaire',
            field=models.TextField(default='RAS', max_length=50),
        ),
    ]
