# Generated by Django 4.0.8 on 2023-08-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_systematique_gb_systematique_hb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systematique',
            name='commentaire',
            field=models.TextField(default='RAS', max_length=100),
        ),
    ]
