# Generated by Django 4.0.8 on 2023-08-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_systematique_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='minimum_stock',
        ),
    ]
