# Generated by Django 4.0.8 on 2023-08-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_medicine_minimum_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancemedicine',
            name='minimum_stock',
        ),
    ]
